<a href="https://colab.research.google.com/github/pedro141122/Basic-Model/blob/main/Graded_Quiz_Intro_to_Python_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Question 3
array  = ([[94, 89, 63],

             [93, 92, 48],

             [92, 94, 56]])

In [8]:
import numpy as np

In [6]:
print(array)

[[94, 89, 63], [93, 92, 48], [92, 94, 56]]


In [11]:
a=np.array([[94, 89, 63],[93, 92, 48],[92, 94, 56]])

In [13]:
print(a)

[[94 89 63]
 [93 92 48]
 [92 94 56]]


In [21]:
a[0,1:]

array([89, 63])

This question is not clear. The numbers in italics is not clear. I think italicized numbers are 89 and 63.

In [26]:
#Question 5
y = [(2, 4), (7, 8), (1, 5, 9)]

In [27]:
x=y[1][-1]
print(x)

8


In [33]:
import pandas as pd

In [34]:
#Question 9
lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]

col = ['Age','Nationality','Overall']

In [38]:
df=pd.DataFrame(lst, columns=col,index=[1,2,3])
print(df)

   Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92


In [39]:
#Question 17
my_tuppy = (1,2,5,8)

In [40]:
my_tuppy[2] = 6

TypeError: ignored

In [41]:
#Question 18
S = [['him', 'sell'], [90, 28, 43]]

In [42]:
S[0][1][1]

'e'

In [54]:
#I could not load the file from food and agriculture association. See error below

In [56]:
df = pd.read_csv("C:\Users\BGP001\Downloads\FoodBalanceSheets_E_Africa_NOFLAG", encoding = "latin-1")

SyntaxError: ignored

In [57]:
df = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG", encoding = "latin-1")

FileNotFoundError: ignored

In [63]:
df = pd.read_csv("C:\Users\BGP001\Desktop\FoodBalanceSheets_E_Africa_NOFLAG", encoding = "latin-1", header=0, delimiter=r'\t',quoting=3)

SyntaxError: ignored